#!/usr/bin/env python3
"""
wav_to_c.py — Convert pre-recorded response .wav files into a C header that
embeds them as int16_t arrays in Flash.

Usage:
    python3 wav_to_c.py responses/*.wav -o src/tts/response_clips.h

The output replaces src/tts/response_clips.h. The audio playback subsystem
and TTS lookup code expect every clip to be:

    * 16-bit signed PCM
    * 16 kHz sample rate
    * mono

Files that don't match are rejected loudly rather than silently resampled —
resampling on the host gives much better results, so do it in Audacity /
ffmpeg before running this script.

Each .wav 'foo.wav' yields three identifiers in the generated header:

    extern const int16_t  foo_audio[];
    #define foo_size            <sample count>
    #define foo_duration_ms     <duration in ms>
"""

from __future__ import annotations

import argparse
import os
import sys
import wave
from pathlib import Path
from typing import Iterable, List


SAMPLE_RATE_HZ      = 16000
BITS_PER_SAMPLE     = 16
CHANNELS            = 1
SAMPLES_PER_LINE    = 12   # purely cosmetic for the generated header


def c_identifier(wav_path: Path) -> str:
    """Turn 'responses/joke_001.wav' into 'joke_001'."""
    name = wav_path.stem
    cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def read_wav(wav_path: Path) -> List[int]:
    """Read a .wav file, validate format, return list of int16 samples."""
    with wave.open(str(wav_path), "rb") as wav:
        n_channels   = wav.getnchannels()
        samp_width   = wav.getsampwidth()
        frame_rate   = wav.getframerate()
        n_frames     = wav.getnframes()

        if n_channels != CHANNELS:
            raise ValueError(
                f"{wav_path}: expected mono ({CHANNELS} channel), "
                f"got {n_channels}"
            )
        if samp_width * 8 != BITS_PER_SAMPLE:
            raise ValueError(
                f"{wav_path}: expected {BITS_PER_SAMPLE}-bit PCM, "
                f"got {samp_width * 8}-bit"
            )
        if frame_rate != SAMPLE_RATE_HZ:
            raise ValueError(
                f"{wav_path}: expected {SAMPLE_RATE_HZ} Hz, got {frame_rate} Hz"
            )

        raw = wav.readframes(n_frames)

    samples: List[int] = []
    for i in range(0, len(raw), 2):
        samples.append(int.from_bytes(raw[i:i + 2], "little", signed=True))
    return samples


def emit_array(name: str, samples: List[int], src_path: Path) -> str:
    """Render a single clip as a C array + size/duration #defines."""
    duration_ms = (len(samples) * 1000) // SAMPLE_RATE_HZ

    out = []
    out.append(f"/* Generated from {src_path.as_posix()} "
               f"({len(samples)} samples, {duration_ms} ms) */")
    out.append(f"const int16_t {name}_audio[] = {{")

    for i in range(0, len(samples), SAMPLES_PER_LINE):
        chunk = samples[i:i + SAMPLES_PER_LINE]
        line = ", ".join(f"{s:6d}" for s in chunk)
        out.append(f"    {line},")

    out.append("};")
    out.append(f"#define {name}_size           "
               f"((uint32_t)(sizeof({name}_audio) / sizeof(int16_t)))")
    out.append(f"#define {name}_duration_ms    ((uint16_t){duration_ms}u)")
    out.append("")
    return "\n".join(out)


HEADER_PROLOGUE = """\
/**
 * @file    response_clips.h
 * @brief   Embedded PCM audio for pre-recorded responses.
 *
 * AUTO-GENERATED by tools/wav_to_c.py — DO NOT EDIT BY HAND.
 *
 * Format for every clip: 16-bit signed PCM, 16 kHz, mono.
 */

#ifndef COSMO_TTS_RESPONSE_CLIPS_H
#define COSMO_TTS_RESPONSE_CLIPS_H

#include <stdint.h>

"""

HEADER_EPILOGUE = """
#endif /* COSMO_TTS_RESPONSE_CLIPS_H */
"""


def generate_header(wav_paths: Iterable[Path]) -> str:
    blocks = [HEADER_PROLOGUE]
    for wav_path in wav_paths:
        ident   = c_identifier(wav_path)
        samples = read_wav(wav_path)
        blocks.append(emit_array(ident, samples, wav_path))
    blocks.append(HEADER_EPILOGUE)
    return "\n".join(blocks)


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("inputs", nargs="+",
                        help="Input .wav files (16 kHz / 16-bit / mono)")
    parser.add_argument("-o", "--output",
                        default="src/tts/response_clips.h",
                        help="Output header path "
                             "(default: src/tts/response_clips.h)")
    args = parser.parse_args(argv)

    wav_paths = [Path(p) for p in args.inputs]
    for p in wav_paths:
        if not p.is_file():
            print(f"error: {p} not found", file=sys.stderr)
            return 1

    try:
        header_text = generate_header(wav_paths)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header_text, encoding="utf-8")

    total_samples = sum(len(read_wav(p)) for p in wav_paths)
    total_bytes   = total_samples * 2
    print(f"wrote {out_path} "
          f"({len(wav_paths)} clips, {total_samples} samples, "
          f"{total_bytes / 1024:.1f} KB Flash)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
