/**
 * @file    response_clips.h
 * @brief   Embedded PCM audio for pre-recorded responses.
 *
 * AUTO-GENERATED by tools/wav_to_c.py from .wav source files. Do not edit by
 * hand. To regenerate after recording new clips:
 *
 *     python3 tools/wav_to_c.py responses/<all>.wav -o inc/response_clips.h
 *
 * Format for every clip: 16-bit signed PCM, 16 kHz, mono.
 *
 * NOTE: The arrays below are stub placeholders so the code compiles and links
 * without the real .wav files. Replace this header by re-running the script
 * once the recordings are in place. Each placeholder is ~200 ms of silence
 * with a short ramp so it's safe to feed straight into the DAC.
 */

#ifndef COSMO_TTS_RESPONSE_CLIPS_H
#define COSMO_TTS_RESPONSE_CLIPS_H

#include <stdint.h>

/* Each placeholder array is 3200 samples = 200 ms @ 16 kHz. Real clips will
 * be substantially larger (a 3-second clip is 48000 samples / 96 KB).        */
#define TTS_PLACEHOLDER_SAMPLES   3200U
#define TTS_PLACEHOLDER_DURATION  200U   /* ms */

/* Single shared silence buffer keeps Flash use sane while the .wav recording
 * pipeline is being set up. The conversion script replaces this header
 * entirely with one array per clip.                                          */
extern const int16_t tts_placeholder_silence[TTS_PLACEHOLDER_SAMPLES];

/* ── Greetings ───────────────────────────────────────────────────────────── */
#define greeting_001_audio          tts_placeholder_silence
#define greeting_001_size           TTS_PLACEHOLDER_SAMPLES
#define greeting_001_duration_ms    TTS_PLACEHOLDER_DURATION

#define greeting_002_audio          tts_placeholder_silence
#define greeting_002_size           TTS_PLACEHOLDER_SAMPLES
#define greeting_002_duration_ms    TTS_PLACEHOLDER_DURATION

#define greeting_003_audio          tts_placeholder_silence
#define greeting_003_size           TTS_PLACEHOLDER_SAMPLES
#define greeting_003_duration_ms    TTS_PLACEHOLDER_DURATION

/* ── Jokes ───────────────────────────────────────────────────────────────── */
#define joke_001_audio              tts_placeholder_silence
#define joke_001_size               TTS_PLACEHOLDER_SAMPLES
#define joke_001_duration_ms        TTS_PLACEHOLDER_DURATION

#define joke_002_audio              tts_placeholder_silence
#define joke_002_size               TTS_PLACEHOLDER_SAMPLES
#define joke_002_duration_ms        TTS_PLACEHOLDER_DURATION

#define joke_003_audio              tts_placeholder_silence
#define joke_003_size               TTS_PLACEHOLDER_SAMPLES
#define joke_003_duration_ms        TTS_PLACEHOLDER_DURATION

/* ── Goodbye ─────────────────────────────────────────────────────────────── */
#define goodbye_001_audio           tts_placeholder_silence
#define goodbye_001_size            TTS_PLACEHOLDER_SAMPLES
#define goodbye_001_duration_ms     TTS_PLACEHOLDER_DURATION

#define goodbye_002_audio           tts_placeholder_silence
#define goodbye_002_size            TTS_PLACEHOLDER_SAMPLES
#define goodbye_002_duration_ms     TTS_PLACEHOLDER_DURATION

/* ── Fallback / error ────────────────────────────────────────────────────── */
#define fallback_001_audio          tts_placeholder_silence
#define fallback_001_size           TTS_PLACEHOLDER_SAMPLES
#define fallback_001_duration_ms    TTS_PLACEHOLDER_DURATION

#define error_001_audio             tts_placeholder_silence
#define error_001_size              TTS_PLACEHOLDER_SAMPLES
#define error_001_duration_ms       TTS_PLACEHOLDER_DURATION

#endif /* COSMO_TTS_RESPONSE_CLIPS_H */
